apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./system
  interval: 1m0s
  prune: true
