apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- github-status-alert.yaml
- kustomization-system.yaml
# - kustomization-apps.yaml
