apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8s-apps
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  interval: 10m0s
  prune: true
