apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/external-dns
  chart: external-dns
  version: 1.13.1
  targetNamespace: external-dns
  createNamespace: true
  valuesContent: |-
    extraArgs:
      - --publish-internal-services
      - --zone-id-filter=3835c3e80320e08ac9fadad86e96b3d5
    provider: cloudflare
    policy: sync
    logLevel: debug
    txtOwnerId: k8s.pokgak.xyz
    domainFilters: k8s.pokgak.xyz
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-auth
            key: CF_API_TOKEN

