apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-dns
  namespace: kube-system
spec:
  repo: https://kubernetes-sigs.github.io/external-dns
  chart: external-dns
  version: 1.13.1
  targetNamespace: external-dns
  createNamespace: true
  valuesContent: |-
    provider: cloudflare
    policy: sync
    logLevel: debug
    txtOwnerId: k8s.pokgak.xyz
    domainFilters: k8s.pokgak.xyz
    extraArgs: ["--publish-internal-services"]
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-auth
            key: CF_API_TOKEN

